/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab4;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;


public class lab4_bai1_menu extends javax.swing.JFrame {

    public lab4_bai1_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgColor = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        edPage = new javax.swing.JEditorPane();
        txtFpoly = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnFileNew = new javax.swing.JMenuItem();
        mnFileOpen = new javax.swing.JMenuItem();
        mnFileSave = new javax.swing.JMenuItem();
        mnColor = new javax.swing.JMenu();
        mnColorRed = new javax.swing.JRadioButtonMenuItem();
        mnColorGreen = new javax.swing.JRadioButtonMenuItem();
        mnColorBlue = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnColorTextColor = new javax.swing.JMenuItem();
        mnSystem = new javax.swing.JMenu();
        mnAbout = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Java 3");

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/New.png"))); // NOI18N
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNew);

        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/user.png"))); // NOI18N
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAbout);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/shut_down.png"))); // NOI18N
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        jScrollPane2.setViewportView(edPage);

        txtFpoly.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtFpoly.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFpoly.setText("Fpoly - Java 3");

        mnFile.setText("File");

        mnFileNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/document-32.png"))); // NOI18N
        mnFileNew.setMnemonic('N');
        mnFileNew.setText("New");
        mnFileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileNewActionPerformed(evt);
            }
        });
        mnFile.add(mnFileNew);

        mnFileOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/open-file.png"))); // NOI18N
        mnFileOpen.setMnemonic('O');
        mnFileOpen.setText("Open");
        mnFileOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileOpenActionPerformed(evt);
            }
        });
        mnFile.add(mnFileOpen);

        mnFileSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnFileSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab4/file-zip-alt-32.png"))); // NOI18N
        mnFileSave.setMnemonic('S');
        mnFileSave.setText("Save");
        mnFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnFileSaveActionPerformed(evt);
            }
        });
        mnFile.add(mnFileSave);

        jMenuBar1.add(mnFile);

        mnColor.setText("Color");

        bgColor.add(mnColorRed);
        mnColorRed.setSelected(true);
        mnColorRed.setText("Red");
        mnColorRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorRedActionPerformed(evt);
            }
        });
        mnColor.add(mnColorRed);

        bgColor.add(mnColorGreen);
        mnColorGreen.setText("Green");
        mnColorGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorGreenActionPerformed(evt);
            }
        });
        mnColor.add(mnColorGreen);

        bgColor.add(mnColorBlue);
        mnColorBlue.setText("Blue");
        mnColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorBlueActionPerformed(evt);
            }
        });
        mnColor.add(mnColorBlue);
        mnColor.add(jSeparator1);

        mnColorTextColor.setText("Text Color");
        mnColorTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnColorTextColorActionPerformed(evt);
            }
        });
        mnColor.add(mnColorTextColor);

        jMenuBar1.add(mnColor);

        mnSystem.setText("System");

        mnAbout.setText("About us");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        mnSystem.add(mnAbout);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnSystem.add(mnExit);

        jMenuBar1.add(mnSystem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addGap(182, 182, 182))
            .addComponent(jScrollPane2)
            .addComponent(txtFpoly)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtFpoly, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnFileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileNewActionPerformed
        // TODO add your handling code here:
        edPage.setText("");
    }//GEN-LAST:event_mnFileNewActionPerformed

    private void mnFileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileOpenActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooser = new JFileChooser();
//        FileNameExtensionFilter filer = new FileNameExtensionFilter("HTM or HTML files / Web pages", "htm","html");
//        fchooser.setFileFilter(filer);
        int result = fchooser.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION){
            try {
                edPage.setPage("file:///" + fchooser.getSelectedFile().getPath());
                //JOptionPane.showMessageDialog(null, fchooser.getSelectedFile().getPath());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnFileOpenActionPerformed
    
    private void mnFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnFileSaveActionPerformed
        // TODO add your handling code here:
          JFileChooser fChooser = new JFileChooser();
          int result = fChooser.showSaveDialog(null);
          if(result==JFileChooser.APPROVE_OPTION){
            File fname = fChooser.getSelectedFile();
            try {
              PrintWriter pw = new PrintWriter(fname);
              pw.println(edPage.getText());
              pw.close();
            } catch (Exception ex) {
              ex.printStackTrace();
            }
          }
    }//GEN-LAST:event_mnFileSaveActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        // TODO add your handling code here:
        showAboutUs();
    }//GEN-LAST:event_mnAboutActionPerformed
    private void showAboutUs(){
          String str ="Program Demo Menu";
          str+="\nAuthor: TheHuy";
          str+="\nLast Update: 29-03-2003";
          str+="\nEducation: Fpoly";
          JOptionPane.showMessageDialog(null, str,"Gioi thieu",JOptionPane.INFORMATION_MESSAGE);
    }
    private void mnColorRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorRedActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.red);
    }//GEN-LAST:event_mnColorRedActionPerformed

    private void mnColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorGreenActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.green);
    }//GEN-LAST:event_mnColorGreenActionPerformed

    private void mnColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorBlueActionPerformed
        // TODO add your handling code here:
        txtFpoly.setBackground(Color.blue);
    }//GEN-LAST:event_mnColorBlueActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        // TODO add your handling code here:
        showAboutUs();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        edPage.setText("");
    }//GEN-LAST:event_btnNewActionPerformed

    private void mnColorTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnColorTextColorActionPerformed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Chon mau chu", Color.white);
        txtFpoly.setForeground(c);
    }//GEN-LAST:event_mnColorTextColorActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab4_bai1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab4_bai1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab4_bai1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab4_bai1_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab4_bai1_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgColor;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNew;
    private javax.swing.JEditorPane edPage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenu mnColor;
    private javax.swing.JRadioButtonMenuItem mnColorBlue;
    private javax.swing.JRadioButtonMenuItem mnColorGreen;
    private javax.swing.JRadioButtonMenuItem mnColorRed;
    private javax.swing.JMenuItem mnColorTextColor;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnFileNew;
    private javax.swing.JMenuItem mnFileOpen;
    private javax.swing.JMenuItem mnFileSave;
    private javax.swing.JMenu mnSystem;
    private javax.swing.JTextField txtFpoly;
    // End of variables declaration//GEN-END:variables
}
